version: "3.8"

services:
  client:
    container_name: client
    build:
      context: ../client
    volumes:
      - ../client:/app
    ports:
      - "3000:3000"

  api:
    container_name: api
    build:
      context: ../api
    volumes:
      - ../api:/app
    ports:
      - "8000:8000"
